# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock

# 2. Installed Gems
plugins:
- jekyll-paginate

# 3. Gem settings
paginate: 500000 # jekyll-paginate > items per page
paginate_path: page:num # jekyll-paginate > blog page

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Asia/Kolkata # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Homepage #Needed for Siteleaf
    output: true
#     description: "This is merely a demo, find out more [about Garth](about)" # The post list page content

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Kanishk Kakar" # Site name or title
# favicon: "/favicon.ico" # Uncomment to add custom favicon, or leave as is to use site logo
description: "Kanishk's website" # Site description and default description
url: "http://kanishkkakar.com" # Site url
baseurl: ""
lang: en-GB
